[changelog]
header = """
# Changelog\n
All significant updates and improvements\n
"""
body = """
{% if version %}\
    ## v{{ version | trim_start_matches(pat="v") }}

    Released on: {{ timestamp | date(format="%b %-d, %Y") }}
{% else %}\
    ## Upcoming version
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
            {% if commit.author.name %}
              · by {{ commit.author.name }}
            {%- endif %}\
            {% if commit.remote.username %}
              ([@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username }}))
            {%- endif %}\
            {% if commit.id %}
              ([{{ commit.id | truncate(length=7, end="") }}](<REPO>/commit/{{ commit.id }}))
            {% else %}
              ({{ commit.id | truncate(length=7, end="") }})
            {% endif %}\
    {% endfor %}
{% endfor %}\n
"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true
postprocessors = [
  { pattern = '<REPO>', replace = "https://github.com/sanusart/react-dropdown-select" },
]

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
]
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->🚀 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
  { message = "^style", group = "<!-- 5 -->🎨 Styling" },
  { message = "^typo", group = "<!-- 6 -->🔤 Grammar" },
  { message = "^test", group = "<!-- 7 -->🧪 Testing" },
  { message = "^i18n", group = "<!-- 8 -->🌍 Translations" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore: release v?\\d+\\.\\d+\\.\\d+$", skip = true },
  { message = "^chore: update changelog", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^Bump ", skip = true },
  { message = "^Signed-off-by: ", skip = true },
  { message = "^Co-authored-by: ", skip = true },
  { message = "See changelog: https://github.com", skip = true },
  { message = "^chore", group = "<!-- 9 -->⚙️ Miscellaneous Tasks" },
  { message = "^ci", group = "<!-- 10 -->👷 Continuous Integration" },
  { message = "^build", group = "<!-- 11 -->🛠️️ Build" },
  { body = ".*security", group = "<!-- 12 -->🛡️ Security" },
  { message = "^revert", group = "<!-- 13 -->◀️ Revert" },
  { message = ".*", group = "<!-- 14 -->💼 Other" },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"
