name: Node.js Package

on:
  workflow_run:
    workflows: ["Automate Release"]
    types:
      - completed

jobs:
  publish-npm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - run: pnpm install
      - run: pnpm test -- --maxWorkers=2 --maxConcurrent=2
      - run: pnpm run build
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
